#!/bin/bash
#SBATCH -n 24
#SBATCH -t 1:00:00
#SBATCH -p short

# loading modules
module load eb
module loade Miniconda2

# loading virtual environment
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# group significance provides an assessment of statistical significance of differences between OTU abundance with respect to metadata categories.

# testing group significance for pH
echo "group significance"
group_significance.py \
-i ~/18x/tax_mapping/otu_table_L2.biom \
-m ~/18x/map_excl.tsv \
-c SamplePh \
-s kruskal_wallis \
-o grp_sig_pH.txt

# testing group significance for nitrogen
echo "group significance"
group_significance.py \
-i ~/18x/tax_mapping/otu_table_L2.biom \
-m ~/18x/map_excl.tsv \
-c SampleNitrogen \
-s kruskal_wallis \
-o grp_sig_N.txt


# testing group significance for phosphorus
echo "group significance"
group_significance.py \
-i ~/18x/tax_mapping/otu_table_L2.biom \
-m ~/18x/map_excl.tsv \
-c SamplePhosphorus \
-s kruskal_wallis \
-o grp_sig_P.txt


# testing group significance for potassium
echo "group significance"
group_significance.py \
-i ~/18x/tax_mapping/otu_table_L2.biom \
-m ~/18x/map_excl.tsv \
-c SamplePotassium \
-s kruskal_wallis \
-o grp_sig_K.txt

# deactivating virtual environment
source deactivate
