#!/bin/bash
#SBATCH -t 30
#SBATCH -n 24
#SBATCH -p short

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading modules
module load eb
module load Miniconda2

# loading virtual environment
source deactivate
source activate qiime1

echo "compare categories"
time compare_categories.py \
--method anosim \
-i ~/18x/cdout_acido/bdiv_even1723/unweighted_unifrac_dm.txt \
-m ~/18x/map_excl.tsv \
-c SamplePh \
-o ~/18x/Xph \
-n 99

time compare_categories.py \
--method anosim \
-i ~/18x/cdout_acido/bdiv_even1723/unweighted_unifrac_dm.txt \
-m ~/18x/map_excl.tsv \
-c SamplePotassium \
-o ~/18x/Xpot \
-n 99

time compare_categories.py \
--method anosim \
-i ~/18x/cdout_acido/bdiv_even1723/unweighted_unifrac_dm.txt \
-m ~/18x/map_excl.tsv \
-c SamplePhosphorus \
-o ~/18x/Xphos \
-n 99

time compare_categories.py \
--method anosim \
-i ~/18x/cdout_acido/bdiv_even1723/unweighted_unifrac_dm.txt \
-m ~/18x/map_excl.tsv \
-c SampleNitrogen \
-o ~/18x/Xnitro \
-n 99

# deactivating virtual environment
source deactivate
