#!/bin/bash
#SBATCH -t 30
#SBATCH -n 24
#SBATCH -p short

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading modules
module load eb
module load Miniconda2

# loading virtual environment
source deactivate
source activate qiime1

# merge BIOM-formated tables
merge_otu_tables.py \
-i /home/cbmucl04/16/otus/otu_table.biom,/home/cbmucl04/17/otus/otu_table.biom,/home/cbmucl04/18x/otus/otu_table.biom \
-o ~/18x/merged_otu_table.biom

# deactivating virtual environment
source deactivate
