#!/bin/bash
#SBATCH -t 30
#SBATCH -n 24
#SBATCH -p short

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading modules and virtual environment
module load eb
module load Miniconda2
source deactivate
source activate qiime1

# compare diversity of samples with respect to year
echo "compare categories"
time compare_categories.py \
--method anosim \
-i ~/18x/cdout_merged_acido/bdiv_even1723/unweighted_unifrac_dm.txt \
-m ~/18x/map_merged.tsv \
-c Year \
-o ~/18x/Year \
-n 99

# deactivating virtual environment
source deactivate
