#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading modules
module load eb
module load Miniconda2

# loading virtual environment
source deactivate
source activate qiime1

# checking mapping file for errors
echo "validate mapping file"
time validate_map.py \
-i ~/17/map.tsv
-o ~/17/vmf

# demultiplexing and quality filtering
echo "demulitplex and quality filter"
time split_libraries_fastq.py \
-i ~/17/Read1.fastq.gz \
-b ~/17/Index.fastq.gz \
-m ~/17/map.tsv \
-q 19 \
-o ~/17/slout \
--barcode_type 12 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

# picking OTUs with Silva reference database
echo "pick OTUs with Silva"
time pick_closed_reference_otus.py \
-i ~/17/slout/seqs.fna \
-o ~/17/otus \
-a -O 24

# summarizing OTU table generated
echo "summarize OTU table"
time biom summarize-table \
-i ~/17/otus/otu_table.biom

# running core diversity analyses
echo "core diversity analyses"
time core_diversity_analyses.py \
--recover_from_failure \
-i ~/17/otus/otu_table.biom \
-m ~/17/map.tsv \
-t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-o ~/17/cdout \
-e 30000 \
-a -O 24

# deactivating virtual environment
source deactivate
