#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal 

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading modules"
module load eb
module load Miniconda2

echo "loading virtual environment"
source deactivate
source activate qiime1

echo "validate mapping file
time validate_map.py \
-i ~/18/map.tsv
-o ~/2018/vmf

echo "joining paired reads with SeqPrep"
time join_paired_ends.py \
-m SeqPrep \
-f ~/18/Read1.fastq.gz \
-r ~/18/Read2.fastq.gz \
-b ~/18/Index.fastq.gz \
-o ~/jpe

echo "demulitplexing and quality filtering"
time split_libraries_fastq.py \
-i ~/18/jpe/seqprep_assembled.fastq.gz \
-b ~/18/jpe/seqprep_assembled.fastq_barcodes.fastq \
-m ~/18/map.tsv -q 19 \
-o ~/18/slout \
--rev_comp_barcode \
--rev_comp_mapping_barcodes


echo "picking OTUs with Silva"
time pick_closed_reference_otus.py \
-i ~/18/slout/seqs.fna \
-o ~/18/otus \
-a -O 24

echo "summarizing OTU table"
time biom summarize-table \
-i ~/18/otus/otu_table.biom

echo "core diversity analyses"
time core_diversity_analyses.py \
--recover_from_failure \
-i ~/18/otus/otu_table.biom \
-m ~/18/map.tsv \
-t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-o ~18/cdout
-e 30000 \
-a -O 24

echo "deactivating qiime"
source deactivate
