#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# loading modules
module load eb
module load Miniconda2

# loading virtual environment
source deactivate
source activate qiime1

# checking mapping file for errors
echo "validate mapping file"
-i ~/18/map.tsv
-o ~/2018/vmf

# joining paired ends with SeqPrep
echo "join paired reads with SeqPrep"
time join_paired_ends.py \
-m SeqPrep \
-f ~/18/Read1.fastq.gz \
-r ~/18/Read2.fastq.gz \
-b ~/18/Index.fastq.gz \
-o ~/jpe

# demultiplexing and quality filtering
echo "demulitplex and quality filter"
time split_libraries_fastq.py \
-i ~/18/jpe/seqprep_assembled.fastq.gz \
-b ~/18/jpe/seqprep_assembled.fastq_barcodes.fastq \
-m ~/18/map.tsv -q 19 \
-o ~/18/slout \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

# picking OTUs with Silva reference database
echo "pick OTUs with Silva"
time pick_closed_reference_otus.py \
-i ~/18/slout/seqs.fna \
-o ~/18/otus \
-a -O 24

# summarizing OTU table generated
echo "summarize OTU table"
time biom summarize-table \
-i ~/18/otus/otu_table.biom

# running core diversity analyses
echo "core diversity analyses"
time core_diversity_analyses.py \
--recover_from_failure \
-i ~/18/otus/otu_table.biom \
-m ~/18/map.tsv \
-t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-o ~18/cdout
-e 30000 \
-a -O 24

# deactivating virtual environment
source deactivate
