#!/bin/bash
#SBATCH -t 30
#SBATCH -n 24
#SBATCH -p short

# load modules to run python
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# validate mapping file
echo "validate mapping file"
time validate_mapping_file.py \
-m ~/2018/map.tsv \
-o ~/2018/vmf

# deactivating environment
source deactivate





# join paired ends

#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
module load eb
module load Miniconda2
source activate qiime1
export TMPDIR=~/qiime_tmp
echo "join paired ends"
time join_paired_ends.py \
-m SeqPrep \
-b ~/2018/Index.fastq.gz \
-f ~/2018/Read1.fastq.gz \
-r ~/2018/Read2.fastq.gz \
-o ~/2018/jpe
source deactivate





# demultiplexing

#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
module load eb
module load Miniconda2
source activate qiime1
export TMPDIR=~/qiime_tmp
echo "demultiplexing"
split_libraries_fastq.py \
-m ~/2018/map.tsv \
-i ~/2018/jpe/seqprep_assembled.fastq.gz \
-b ~/2018/jpe/seqprep_assembled.fastq_barcodes.fastq \
-o ~/2018/slout \
-q 19 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes
source deactivate





