#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

echo "set temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "load modules"
module load eb
module load Miniconda2

echo "load virtual environment"
source deactivate
source activate qiime1

# create 2d plots from weighted unifrac distance matrix
echo "2d plots"
time make_2d_plots.py \
-i ~/18x/cdout/bdiv_even30000/weighted_unifrac_pc.txt \
-m ~/18x/map_excl.tsv \
-o ~/18x/2dplots

# echo "deactivate virtual environment"
source deactivate
